def load_apostrophes():
    return apostrophes

#list of informal words containing apostrophes
apostrophes = dict({
    "don't": "do not",
    "can't": "can not",
    "it's": "it is",
    "i'm": "i am",
    "world's": "world",
    "bird's-eye": "bird eye",
    "president's": "president",
    "there's": "there is",
    "doesn't": "does not",
    "they're": "they are",
    "factory's": "factory",
    "we're": "we are",
    "companies'": "companies",
    "won't": "will not",
    "that's": "that is",
    "person's": "person",
    "what's": "what is",
    "designer's": "designer",
    "you're": "you are",
    "you've": "you have",
    "customer's": "customer",
    "individual's": "individual",
    "children's": "children",
    "administration's": "administration",
    "you'll": "you will",
    "let's": "let us",
    "department's": "department",
	"people's": "people",
	"haven't": "have not",
	"didn't": "did not",
	"company's": "company",
	"other's": "other",
	"customers'": "customer",
	"manager's": "manager",
	"manufacturer's": "manufacturer",
	"isn't": "is not",
	"members'": "member",
	"product's": "product",
	"market's": "market",
	"wouldn't": "would not",
	"partners'": "partner",
	"user's": "user",
	"employees'": "employee",
	"everyone's": "everyone"})